# Pipeline for provisioning and deployment of infrastructure.

trigger: none

variables:
  terraformStateName: terraformState
  terraformStateVersion: 1.0
  databaseBackupName: databaseBackup
  databaseBackupVersion: 1.0

# If setting up the whole infra for the first time
  freshSetup: true

resources:
 pipelines:
  - pipeline: FrontEndPipeline   
    source: ziaurrehman72.hello-rest-api
    trigger: 
      branches:
      - refs/heads/master
  - pipeline: BackEndPipeline   
    source: ziaurrehman72.hello-fe 
    trigger: 
      branches:
      - refs/heads/main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo Creating Directory 'terraform'
    mkdir terraform
    echo Creating Directory 'database'
    mkdir database
  displayName: 'Create directory structure'


- task: DownloadPackage@1
  displayName: Download Terraform State file
  condition: eq(freshSetup, true)
  inputs:
    packageType: 'upack'
    feed: '861dcca4-4ec2-450d-9a1e-3da6589aaed3/88f2c9de-f3d7-411b-8a5b-eff9807a7bcc'
    definition: $(terraformState)
    version: $(terraformStateVersion)
    downloadPath: 'terraform/'
    extract: true


- task: DownloadPackage@1
  displayName: Download datbase backup
  condition: eq(freshSetup, true)
  inputs:
    packageType: 'upack'
    feed: '861dcca4-4ec2-450d-9a1e-3da6589aaed3/3f5ab7a3-6c73-4098-894f-ddfcfac00b01'
    definition: $(databaseBackup)
    version: $(databaseBackupVersion)
    downloadPath: 'database/'
    extract: true

