# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
resources:
 pipelines:
  - pipeline: FrontEndPipeline   
    source: ziaurrehman72.hello-rest-api
    trigger: 
      branches:
      - refs/heads/master
  - pipeline: BackEndPipeline   
    source: ziaurrehman72.hello-fe 
    trigger: 
      branches:
      - refs/heads/main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo Creating Directory 'terraform'
    mkdir terraform
    echo Creating Directory 'database'
    mkdir database
  displayName: 'Create directory structure'


- task: DownloadPackage@1
  displayName: Download Terraform State file
  inputs:
    packageType: 'upack'
    feed: '861dcca4-4ec2-450d-9a1e-3da6589aaed3/88f2c9de-f3d7-411b-8a5b-eff9807a7bcc'
    definition: 'terraformState'
    version: '1.0'
    downloadPath: 'terraform/'
    extract: true


- task: DownloadPackage@1
  inputs:
    packageType: 'upack'
    feed: '861dcca4-4ec2-450d-9a1e-3da6589aaed3/3f5ab7a3-6c73-4098-894f-ddfcfac00b01'
    definition: 'databaseBackup'
    version: '1.0'
    downloadPath: 'database/'
    extract: true
